version: '3.9'

name: identity

services:
  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: identity
      POSTGRES_DB: identity
    ports:
      - 5432:5432
    volumes:
      - ./db-init.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
      - ./db-schema.sql:/docker-entrypoint-initdb.d/db-schema.sql:ro

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: database_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: identity
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - 15432:8080
    depends_on:
      - db